### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by jpkolind** [driftyco/cordova-plugin-wkwebview-engine#3]
When enabling wkwebview, requests to a webserver are from "null" and therefore rejected even with Access-Control-Allow-Origin set to *

**Comment by jgw96** [comment]
Hello! Thanks for opening am issue with us! Would you mind posting a repo that I can use to reproduce this issue? Also, does a request to the same server work without the plugin (on uiwebview) ?

**Comment by jpkolind** [comment]
Unfortunately it is private source. Will try to recreate and send

**Comment by jgw96** [comment]
Thanks, much appreciated!

**Comment by ghenry22** [comment]
I might have a less strict web service that I am connecting to but I have no problems with HTTP requests.  If there is something specific that it's useful to check I can try and log more detail on my server to confirm if that's useful

**Comment by manucorporat** [comment]
@ghenry22 `I have no problems with HTTP requests` so HTTPS?

**Comment by leualemax** [comment]
i`m geting the same error here with the plugin:
![captura de tela 2016-08-19 as 10 58 26](https://cloud.githubusercontent.com/assets/3322092/17812084/f636d4e6-65fb-11e6-80a8-db75c95b04bc.png)

looking forward to use it in prod, nice job guys, you are awesome!

**Comment by ghenry22** [comment]
I'll try HTTPS but won't get time until Monday.

**Comment by calendee** [comment]
Also seeing the  `origin null is not allowed by Access-Control-Allow-Origin`.  

The problem does not exist in the traditional UiWebviuew.

```
Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.
XMLHttpRequest cannot load https://XXXXXXX.com/AuthenticateUser. Origin null is not allowed by Access-Control-Allow-Origin.
```

**Comment by calendee** [comment]
Here's a screenshot showing how the OPTIONS pre-flight has an origin of null.

![xhr-request](https://cloud.githubusercontent.com/assets/57374/17816967/80730972-6601-11e6-86ac-e60bd6aaa35b.png)

**Comment by danbucholtz** [comment]
@calendee, can you take a screenshot of the above with UIWebView?

Thanks,
Dan

**Comment by leualemax** [comment]
it`s not the same request from calendeen, but using UIWebView this is my request:
![captura de tela 2016-08-19 as 14 12 27](https://cloud.githubusercontent.com/assets/3322092/17817846/0562237e-6617-11e6-9d72-e0df1d02c467.png)
using WKWebView i`m getting the same as him.

**Comment by manucorporat** [comment]
@calendee if your server crashing?

**Comment by calendee** [comment]
@manucorporat Nope - no crashing.  The server is just returning 500 because the OPTIONS preflight has null in the origin.  

FYI: In UiWebView, I don't send OPTIONS preflights; so, I don't get this problem and can't screenshot it for you.

**Comment by peterpeterparker** [comment]
In my case I definitely have that error result when Access-Control-Allow-Origin isn't set to *

My node JS server define headers like following:

    res.header("Access-Control-Allow-Origin", "https://mydomain.com");
    res.header("Access-Control-Allow-Credentials", "true");
    res.header("Access-Control-Allow-Headers", "Origin, Authorization, Content-Type, Content-Range, Content-Disposition, Content-Description, X-Requested-With, X-ACCESS_TOKEN");
    res.header("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE");

Which lead to the error we are speaking about with WkWebView. I tried the experiment to change following line and I didn't faced the error anymore, I was able to log in and use my app and own server services with WkWebView.

    res.header("Access-Control-Allow-Origin", "*");

Of course that was only an experiment, because I also use other API that can't make this change and also I'm not really willing to. But in my case, that is the reason for the error "origin null is not allowed by Access-Control-Allow-Origin"

**Comment by mbrookson** [comment]
I am seeing this as well. I've installed the WKWebView plugin, but now web request just don't work because of the Access-Control-Allow-Origin rules which don't matter with UIWebView. The error says `Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin.`

I've tried adding
  `<meta http-equiv="Content-Security-Policy" content="script-src * 'unsafe-eval' 'unsafe-inline'; connect-src * 'unsafe-eval'; object-src *; style-src * 'unsafe-inline'; img-src *">`
to `index.html `but this didn't resolve the issue

**Comment by daviddk** [comment]
Also seeing this problem, It seems WkWebView is just sending out requests with the 'Origin' header set to null. For UiWebView it was set to 'file://' and didn't give any problems.

**Comment by PapyElGringo** [comment]
Same here any solution found on your side guys?

**Comment by willadamskeane** [comment]
I'm having this issue as well.

**Comment by VinKamat** [comment]
Seeing the same issue. Would love to use this plugin. It's as if the most important aspect of an app making http calls is now not possible. Weird.

Error:
`XMLHttpRequest cannot load http://myserver.com/api/login. Origin null is not allowed by Access-Control-Allow-Origin.`

Any workarounds? solutions?

**Comment by danbucholtz** [comment]
All - @manucorporat is working on this bug.  I believe he's AFK for a week or so.  He'll get back to this shortly.

Thanks,
Dan

**Comment by mbrookson** [comment]
That's good news! :)

Bit of a shame to have such a big issue with this straight away which stops many apps from working at all, even after the plugin has had a blog post and is promoted by Ionic. This plugin seems really promising for performance though and looking forward to using it!

**Comment by vuhung3990** [comment]
i have same issue : Origin null is not allowed by Access-Control-Allow-Origin

**Comment by danbucholtz** [comment]
@mbrookson,

Yeah, it's a little unfortunate, but that's why we're asking for beta testers now vs releasing it and saying it's good to go 😄 .  We did test HTTP and didn't have any issues, but it must have been with the way our server was configured.  We are all swamped right now getting Ionic V2 ready to go.  Hopefully, the plugin will be ready for prime time to correspond with Ionic V2 RC.

Thanks for checking it out everyone, the issues submitted so far have been great!

Thanks,
Dan

**Comment by lordgreg** [comment]
Same issue.

**Comment by cvenzin** [comment]
Same here

**Comment by manucorporat** [comment]
I am not in town until January 1st. Are you guys tried debugging this bug server side?
I don't think we can change anything in this plugin to fix this issue (I might be wrong).

http://stackoverflow.com/questions/36000757/cordova-ios-error-origin-null-is-not-allowed-by-access-control-allow-origin

**Comment by lordgreg** [comment]
@manucorporat I'm not getting it. How can this be server-side issue if the REQUEST HEADER is already the one with false header (aka NULL)?

**Comment by mbrookson** [comment]
I understand that you can configure CORS settings on the server side, but I don't particularly want to do that if possible.
Has something changed with the WKWebView which doesn't allow it to work the same as UIWebView because this has never been a problem before?

**Comment by peterpeterparker** [comment]
@manucorporat yes I did some debugging server side, see my comments. 

I don't understand, if you are out of town till next january 1st, someone else gonna have a look at that issue? Or do you mean with that "no, sorry, for the next 6 months, if you face that issue, you can't use the plugin" ... I hope I misunderstood :(

**Comment by danbucholtz** [comment]
@peterpeterparker,

I believe Manu meant September 1st.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz thx for the feedback. I updated my post too.

**Comment by scottopolis** [comment]
Thanks for this guys, I'm excited to use it, but I'm also seeing the CORS issue. With the normal webview, I can access an iframe like this:

var iframedoc = document.getElementById('myApp').contentWindow.document;
var shareBtns = iframedoc.getElementsByClassName('share');

Attempting this with the wkwebview gives me an error referring to the "null" origin that others have mentioned: [Error] Blocked a frame with origin "null" from accessing a frame with origin "http://mysite.com".

I have tried setting CORS headers on my server, and every whitelist configuration possible in config.xml, it does not help.  This issue is definitely related to the wkwebview plugin.

Thanks!

**Comment by ThorConzales** [comment]
@scottopolis same issue here. Trying to access an iframe to call a function in in is being bocked by WKWebView. In the older UIWebView it wasn't a problem.

**Comment by cojj90** [comment]
We have an application that works perfectly on UIWebView published on appstore. Did the drop-in upgrade as per instruction and it fails with CORS error. 

Some note:
- The app fails on the first https call to google (google+ login). 
- We are not using iframe.

**Comment by AllSeeingEye** [comment]
This issue isn't actually an issue, but an "expected" behavior of WKWebView:

https://issues.apache.org/jira/browse/CB-7348

"this is the opposite of what happens in a UIWebView, where a page loaded locally is not restricted to CORS and can do whatever it wants."

So, now both the server and the local app must conform to CORS rules.

**Comment by dorgold** [comment]
@AllSeeingEye 
This is not the problem here, there is no problem with confirming to CORS rules, the problem is the now all the requests are sent with a "null" origin.
Even if my server allows all origins, "null" origin will just won't work.
The webview just needs to send requests with any valid origin (let's say "file://", or anything but "null").

**Comment by cvenzin** [comment]
This is a bug of the WKWebView engine. Origin null is not a valid header. I don't know of any backend that actually can match an origin of null. Sadly the WKWebView Team thinks this is correct and expected behavior ...

**Comment by ThorConzales** [comment]
Couldn't it be overwritten in JS with document.domain property?

**Comment by AllSeeingEye** [comment]
@dorgold understood, sorry.

**Comment by peterpeterparker** [comment]
A couple weeks ago I faced that problem and also noticed, that it was kind of a dead end. 
That's why I thought, gonna repost here: 

that maybe the problem could be solved within the use of a proxy running in the app?

The Ionic team provide an awesome proxy I, maybe we all, use it to debug our app in our local browser (see config ionic.config.json, you know what I mean). Maybe would it be possible to extend this proxy functionality to be allowed to be chipped with our apps?

**Comment by adrinavarro** [comment]
If I get this right, the CORS header is null and therefore it is impossible to do requests from the app to any outside service via http, even though the access control allow origins is set to wildcard on the server side.

This means that this plugin is useless for any apps that require access to remote data via http to work.

Any updates? We really want to use this plugin, but being unable to do external requests due to the invalid origin, we have our hands tied to the old UIWebView.

**Comment by sg1705** [comment]
Yep - The plugin is not useful until CORS issue can be fixed. wkwebview is all we got to make apps perform better on iOS. But given the issues with wkwebview and cordova, it is probably not worth the effort to try to make it work.

Heroic effort from @manucorporat and Ionic though.. kudos!

**Comment by manucorporat** [comment]
@cvenzin  well! it is not. "null" is a valid Origin, probably a server bug ( https://tools.ietf.org/html/rfc6454#section-6.2 ), as I said previously.
I have been very busy fixing other issues in this plugin and in ionic framework. I will try figure out what is going on with WKWebView and CORS, because it does not make sense that some servers work while other don't.

**Comment by sg1705** [comment]
@manucorporat the problem is not of servers. The problem is that when the app (using wkwebview) makes a  request is made, origin is null. Most services like auth0 and firebase don't allow origin as null (since it is not secure, see [issue](https://auth0.com/forum/t/cors-null-for-ionic-v2-ios-build/3598)) and rightly so.

Not sure if we can blame services for rejecting requests from null origin.

**Comment by AllSeeingEye** [comment]
@manucorporat basically, current wkWebView doesn't correct it's behavior (with respect to "origin") when run from the local device. We need a way to correct or, at least, override this behavior.

**Comment by manucorporat** [comment]
@AllSeeingEye @sg1705 I see your point! believe me. But, WK is doing the right thing. "Origin: file://" and stuff like that was never a valid Origin. "null" is. And it should be accepted.

C'mon! They accept "*" but not null, because it is less secure?

>"Not sure if we can blame services for rejecting requests from null origin"

we could blame the standard instead.
```
6.2.  ASCII Serialization of an Origin

   The ascii-serialization of an origin is the value returned by the
   following algorithm:

   1.  If the origin is not a scheme/host/port triple, then return the
       string

          null
```
```
7.3.  User Agent Requirements

   The user agent MAY include an Origin header field in any HTTP
   request.

   The user agent MUST NOT include more than one Origin header field in
   any HTTP request.

   Whenever a user agent issues an HTTP request from a "privacy-
   sensitive" context, the user agent MUST send the value "null" in the
   Origin header field.

      NOTE: This document does not define the notion of a privacy-
      sensitive context.  Applications that generate HTTP requests can
      designate contexts as privacy-sensitive to impose restrictions on
      how user agents generate Origin header fields.
```

Please don't get me wrong, I am actively working right now to find a solution. But it is not as easy as saying, "WKWebView is doing the wrong thing, we have to override it"

**Comment by sg1705** [comment]
@manucorporat , I think you are right here. I saw you posted in auth0 forum. Thanks for looking into this.

**Comment by manucorporat** [comment]
@sg1705 
I want everyone to calm down, we will find a working solution one way or another :)
In the meantime I working in a way to bypass CORS completely. So no, Origin at all!

**Comment by danbucholtz** [comment]
To be clear, we (the Ionic team) did test this with several HTTP frameworks and web services before shipping. It works in some of the more popular web server libraries, but apparently not all.

What server side frameworks are causing trouble with the origin null? It may be useful to know.

Thanks,
Dan

**Comment by pieterbeens** [comment]
@danbucholtz I'm having trouble with Auth0. Login attempts fail with message "Origin null is not allowed."

**Comment by mbrookson** [comment]
I get this issue using .NET Web API

**Comment by chauthai** [comment]
We are having problems with a Wildfly REST API. We have already tried to modify the headers of the responses to have to right origin policies. But still to success.

**Comment by manucorporat** [comment]
@mbrookson @chauthai can you share the code/library are you using exactly to handle CORS?

**Comment by sg1705** [comment]
I am having this problem when I use auth0, firebase3 with Ionic2

**Comment by calendee** [comment]
I think part of the problem is that WkWebView sends an options preflight at all - not just the null origin issue.  Regular UIWebView does not send the options preflight.

**Comment by manucorporat** [comment]
@calendee WOW!

Well, I think we all agree the problem is that WKWebView implements CORS too properly by first time xD

**Comment by wacton** [comment]
This was exactly my problem using .net Web API.

@calendee 
> I think part of the problem is that WkWebView sends an options preflight at all - not just the null origin issue. Regular UIWebView does not send the options preflight.

 Once I ensured that the server accepted the options preflight everything started working.

**Comment by ThorConzales** [comment]
Can you guys also take a look at using iframes locally because currently it is also not working due to CORS issues.

**Comment by chauthai** [comment]
@calendee 
I managed to solve my problems with your tip. XHR-requests to external servers are working now.

Another problem is popping up though:
I can't access local files with XHR, the following error message is coming up:

```
Failed to load resource: Preflight response is not successful 
XMLHttpRequest cannot load file:///var/containers/Bundle/Application/78B2BB53-795F-477C-BB99-70EF595A5992/MyApp.app/www/db-schema.json. Preflight response is not successful
```

We are using `oboe` to read a very big JSON-file as blob.
![screen shot 2016-09-26 at 15 40 52](https://cloud.githubusercontent.com/assets/5654065/18836304/b10b2abc-83ff-11e6-9af4-e25d087aac77.png)

It seems `preflight options` are even mandatory for local file requests when using XHR.

**Comment by manucorporat** [comment]
@chauthai please! can you open a new different issue with all the Xcode / JS logs? thanks!

**Comment by peterpeterparker** [comment]
I know there was a lot to do with the release of the Ionic2 RC.0 ... but any news on this issue? have someone find by any chances a solution or workaround?

**Comment by Manduro** [comment]
Some back-ends seem to disallow the `Origin: null` header sent by WKWebView, but as @manucorporat has mentioned those back-ends are to blame. This plugin just follows the spec.

I'm using Node and I'm having no trouble at all using the following middleware to handle CORS:
```js
function(req, res, next) {
  if (req.headers.origin === 'null') {
    res.setHeader('Access-Control-Allow-Methods', 'GET, PUT, PATCH, POST, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Origin', 'null');
    res.setHeader('Access-Control-Allow-Headers', 'Authorization, Content-Type, Origin');

    if (req.method === 'OPTIONS') {
      res.sendStatus(204);
    } else {
      next();
    }
  } else {
    next();
  }
};
```

**Comment by peterpeterparker** [comment]
thx for your feedback @Manduro 

well, I could set 'Access-Control-Allow-Origin' to '*' (not 'null' because I also access my api from my website), as you did for my server, that will solve the access to my server, I'm agree.

but I'm also using third party services, like the Yelp v2 API, which don't and do not want to allow cors origin. That's why I'm still hoping for a solution or workaround you know...

**Comment by Bouzmine** [comment]
Hi guys, I found something that works on my side to work around our issue. 

- Install [CordovaHTTP](https://github.com/wymsee/cordova-HTTP) (`cordova plugin add cordova-plugin-http`)
- If not already done, update to `ionic-native` to v2.2.0 (if you want to use the wrapper)
- Create a provider which will allow to use the native plugin on the device and Angular's `Http` for developpment in the browser using `ionic serve` ([here](https://github.com/Bouzmine/metho/blob/master/src/providers/reactive-http.ts) is my example, but you could also add a `post` method if needed)
- Use this provider instead of Angular's `Http`

The only problem I have with this implementation is the fact I can't set a custom timeout as I was doing with Angular's `Http`.
I don't know if this workaround could be implemented in the WKWebView plugin to require less (to no) code change by app authors. The CordovaHTTP plugin uses the [AFNetworking](https://github.com/AFNetworking/AFNetworking) library to work.

**Comment by mourice** [comment]
@Bouzmine I tried your solution but getting the empty error response.

Using The below code giving the empty error response.

window.cordovaHTTP.acceptAllCerts(true, function () {
            window.cordovaHTTP.get(ServiceHelper.GetUserGuideUrl(),{},{'Content-Type':'application/json','X-ClientVersion': ServiceHelper.ClientVersion,'X-Source': ServiceHelper.Source,'X-User': GlobalVars.getUserSession().userName, 'X-Locale': ServiceHelper.Locale}, function (response) {
                console.log("success");
            }, function (response) {
                console.log("error");
            });

        }, function () {
            console.log('error :(');
        });
Not getting any hint on whats wrong in the request. Please help

**Comment by zakton5** [comment]
Are there any updates on this?

**Comment by giltig** [comment]
Hi, I have the same problem with origin null error, and before this plugin in the former webview I didnt have the problem.
When a fix is expected?

**Comment by danbucholtz** [comment]
@giltig, @zakton5,

WKWebView enforces CORS so we are switching it to use a null origin. Can you configure your server to accept that header? It should be fine.

Thanks,
Dan

**Comment by giltig** [comment]
You could have just transfer file:// instead.
However there's a bigger problem - why don't u save the cookie - my auth
works with cookies

**Comment by peterpeterparker** [comment]
@danbucholtz it's possible to configure your own server but what about third party servers like Yelp?
They don't support CORS.

https://github.com/Yelp/yelp-fusion/issues/21
https://github.com/Yelp/yelp-fusion/issues/64

**Comment by ThorConzales** [comment]
Whats the progress of accessing local pages through iframes? Have anyone found a workaround for that?

**Comment by zakton5** [comment]
@danbucholtz After talking to our server admins, they said that adding such a header to our server's responses would be unacceptable and pose security risks in production. There must be some other way to get around this beyond modifying the server's response. Besides, in many situations, people do not have access to the server settings anyway.

**Comment by ataraxus** [comment]
Hey Guys, 

i stumbled upon this and it drove me crazy... I suspected cordovas whitelisting to be the issue since the errormsgs on the console look identically on the first glance. 

But whatever, this is apparently the correct behaviour and i managed to configure my JBOSS/RestEasy to coform with it, so i can now use WKWebView, which fixes issues I have with UIWebView!

Nevertheless what bugs me right now is, that this branch states _This branch is 43 commits ahead, 10 commits behind apache:master._ whatever this means. So it would be nice if @danbucholtz or someone from ionic could state which version we should use right now?

**Comment by danbucholtz** [comment]
@ataraxus,

Use this one. This is what we are maintaining. We are working with the Cordova team to get this merged eventually. Please test heavily and let's get this bad boy to a state where we can make this the default.

Thanks,
Dan

**Comment by dalemugford** [comment]
Just wanted to add I'm also stuck with this issue, and it's a deal breaker for WKWebKitView. The performance improvement is soooo worth getting a solution for this. As others mentioned, configuring my server to accept null origin requests doesn't solve accessing other API's I use that I can't configure.

**Comment by manucorporat** [comment]
@dalemugford can you update the plugin? remove all the cordova folder /platform and /plugins

I released WK 2.0 and now it should say: `Origin: ionic.local`

**Comment by dalemugford** [comment]
When I `rm` and install, I see 1.1.2-dev, is that the version?

**Comment by manucorporat** [comment]
@dalemugford I think so, yes. but it is not really a source of truth since this is a fork, and we don't change the version number

**Comment by manucorporat** [comment]
```
rm -rf plugins
rm -rf platforms
cordova platform add ios
```

**Comment by dalemugford** [comment]
Ok, I still get `Failed to load resource: Origin http://ionic.local is not allowed by Access-Control-Allow-Origin.`, even though my server is set to `Access-Control-Allow-Origin: *`

**Comment by AllSeeingEye** [comment]
> I released WK 2.0 and now it should say: Origin: ionic.local
Any way we can set it to `localhost`?

**Comment by dalemugford** [comment]
I'm still getting issues... still trying to work through why, but the same requests in ionic serve or through Postman work.

**Comment by ataraxus** [comment]
@manucorporat great that you are working on it! I couldn't find the 'ionic.local' string in the source and the last few commits also didn't look like this change landed there. Could you please link the commit? 

On more question. I'm aware that this is a fork and the version is fixed, does that mean that the next time our CI server builds our app it will send 'ionic.local' instead 'null'? since that would break the app without any body expecting the issue to be there... I'm just curious, since we go live in a couple of weeks.

**Comment by dalemugford** [comment]
I do see the `ionic.local` but for some reason still it's cranky. In `ionic serve` with the browser set to ignore CORS restrictions everything works fine, on the device I get 403 forbidden errors from the server with the same code. So crappy!

**Comment by manucorporat** [comment]
@dalemugford if your server is returning 403, then it is a server problem... your server should accept it, right?

@ataraxus updating cordova plugins is a mess... I always remove everything (plugins, platforms) and start from scratch
yes, I am sorry for all the changes, but this plugin is not stable yet, and we have to make important changes in order to make it work in all the use cases.

Yes, it will be `ionic.local` or `http://ionic.local` not sure, please test it before releasing and let me know.

Again, excuse the inconveniences and thanks for all the effort testing the plugin!

**Comment by manucorporat** [comment]
@ThorConzales iframes should work too. Can you update and test?

**Comment by dalemugford** [comment]
No problem — I can `POST` perfectly fine from within a `serve` browser environment, everything works fine. Once in the `wkwebkitview`, I receive a a forbidden error, and the reason is that my request for the `Authorization` token is malformed— it says no username was passed— when it was, and the request for JWT works perfectly fine in the serve environment.

So there's something different with with the environment inside the `wkwebkitview`, or maybe there's a `meta http-equiv="Content-Security-Policy` I'm supposed to use in `index.html`?

**Comment by dalemugford** [comment]
For example, this works fine in `serve`, and gets screwy in the `wkwebkitview`:

`	requestToken() {
		let headers = new Headers();
		let options = new RequestOptions({headers: headers});
		let params = new URLSearchParams();
		let storage = new Storage();

		params.set('username', 'findex');
		params.set('password', 'largem0uth');

		let basicParams = {
			username: 'name',
			password: 'password'
		}

		this.http.post('http://www.mysite.com/wp-json/jwt-auth/v1/token', basicParams, options ).subscribe(data => {
			let response = JSON.parse(data['_body']);
			storage.set('token', response.token);
			console.log(response.token);
		}, error => {
			console.log(error); // Error getting the data
		});
	}`

**Comment by dalemugford** [comment]
<img width="298" alt="screen shot 2017-01-25 at 6 57 01 pm" src="https://cloud.githubusercontent.com/assets/20866870/22314566/41fa68e6-e330-11e6-980a-a984e2b9ddec.png">
<img width="285" alt="screen shot 2017-01-25 at 6 56 38 pm" src="https://cloud.githubusercontent.com/assets/20866870/22314568/454507cc-e330-11e6-8fb0-7e15fd38c70f.png">

Just showing the difference between the two requests, `ionic serve` works, inside `wkwebview`, nope.

**Comment by AllSeeingEye** [comment]
@dalemugford any way you can post full request headers for both requests?

**Comment by dalemugford** [comment]
Sure, what's the best way to get them?

**Comment by AllSeeingEye** [comment]
@dalemugford you can easily do it in Chrome developer console. Open it before any requests are made (or just reload the page), switch to the network tab, run the request(s), find the request in the list, click it and copy the Request Headers section.

**Comment by dalemugford** [comment]
Great: here's the success:

`
    * Request URL:http://www.mysite.com/wp-json/jwt-auth/v1/token
    * Request Method:POST
    * Status Code:200 OK
    * Remote Address:66.147.244.184:80
* Response Headersview source
    * Access-Control-Allow-Credentials:true
    * Access-Control-Allow-Headers:Authorization, Content-Type
    * Access-Control-Allow-Methods:OPTIONS, GET, POST, PUT, PATCH, DELETE
    * Access-Control-Allow-Origin:http://localhost:8100
    * Access-Control-Expose-Headers:X-WP-Total, X-WP-TotalPages
    * Allow:POST
    * Connection:keep-alive
    * Content-Encoding:gzip
    * Content-Length:298
    * Content-Type:application/json; charset=UTF-8
    * Date:Thu, 26 Jan 2017 00:16:46 GMT
    * Link:<http://mysite.com/wp-json/>; rel="https://api.w.org/"
    * Server:nginx/1.10.2
    * Vary:Origin,Accept-Encoding
    * X-Content-Type-Options:nosniff
    * X-Robots-Tag:noindex
* Request Headersview source
    * Accept:*/*
    * Accept-Encoding:gzip, deflate
    * Accept-Language:en-US,en;q=0.8
    * Connection:keep-alive
    * Content-Length:54
    * content-type:application/json
    * Host:www.findexapp.com
    * Origin:http://localhost:8100
    * Referer:http://localhost:8100/
    * User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
* Request Payloadview source
        *  {username: “name”, password: “password”}
            * password : "largem0uth" username : "findex" 
        *   `

**Comment by AllSeeingEye** [comment]
@dalemugford ...and the failure one?

**Comment by manucorporat** [comment]
@dalemugford does your server respond to CORS preflight requests?
content-type:application/json
^ application/json are not standard content-type, so WK will perform preflight request with HTTP method OPTIONS.

**Comment by dalemugford** [comment]
You can see here in chrome that the preflight was ok in the browser:

`Request URL:http://www.findexapp.com/wp-json/jwt-auth/v1/token
Request Method:OPTIONS
Status Code:200 OK
Remote Address:66.147.244.184:80
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Authorization, Content-Type
Access-Control-Allow-Methods:OPTIONS, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Origin:http://localhost:8100
Access-Control-Expose-Headers:X-WP-Total, X-WP-TotalPages
Allow:POST
Connection:keep-alive
Content-Encoding:gzip
Content-Length:143
Content-Type:application/json; charset=UTF-8
Date:Thu, 26 Jan 2017 00:16:46 GMT
Link:<http://findexapp.com/wp-json/>; rel="https://api.w.org/"
Server:nginx/1.10.2
Vary:Origin,Accept-Encoding
X-Content-Type-Options:nosniff
X-Robots-Tag:noindex
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:www.findexapp.com
Origin:http://localhost:8100
Referer:http://localhost:8100/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36`

**Comment by manucorporat** [comment]
Just to reduce the area of possible errors, can you replace content-type with Content-Type, some implementations are buggy

**Comment by dalemugford** [comment]
Sure — where do you want me to change that?

**Comment by dalemugford** [comment]
Thx Manu : )

**Comment by manucorporat** [comment]
@dalemugford also!

Note: WebKit Nightly and Safari Technology Preview place additional restrictions on the values allowed in the Accept, Accept-Language, and Content-Language headers. If any of those headers have ”non-standard” values, WebKit/Safari preflights the request. What WebKit/Safari considers “non-standard” values for those headers is not documented except in the following WebKit

https://bugs.webkit.org/show_bug.cgi?id=165178
https://bugs.webkit.org/show_bug.cgi?id=165566
https://bugs.webkit.org/show_bug.cgi?id=166363

Can you add `Accept` and `Accept-Language` to `Access-Control-Allow-Headers` in the preflight response?

**Comment by dalemugford** [comment]
I added `Accept` and `Accept-Language` to the server, but it didn't make a difference. Could the issue have to do with polyfills at all?

**Comment by manucorporat** [comment]
no, the newest version of the WK does not use any polyfill! ok new idea! can you show me your config.xml?

**Comment by dalemugford** [comment]
That's one thing I think might be different— it's ok in safari because it's going through `polyfills.js`, and in wk it's not.

**Comment by manucorporat** [comment]
ah that polyfill! I don't think it is the problem either, can you post your config.xml?

**Comment by dalemugford** [comment]
Here's my config, I justremoved the icons and splash links to shorten it:

`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.ionicframework.findexv4497458" version="0.0.2" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>My App</name>
    <description>My app desc</description>
    <author email="info@myapp.com" href="http://myapp.com/">myapp.com</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="*" />
    <allow-navigation href="*" />
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
       
    </platform>
    <platform name="android">
    
    </platform>
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="220" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="2000" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <engine name="android" spec="~6.1.1" />
    <plugin name="cordova-plugin-whitelist" spec="~1.3.1" />
    <plugin name="cordova-plugin-console" spec="~1.0.5" />
    <plugin name="cordova-plugin-statusbar" spec="~2.2.1" />
    <plugin name="cordova-plugin-device" spec="~1.1.4" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.1" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-x-socialsharing" spec="~5.1.5" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="https://github.com/driftyco/cordova-plugin-wkwebview-engine.git" />
</widget>`

**Comment by manucorporat** [comment]
Ok, do you really need `<access origin="*" />`? if you really need so because you want to connect to different domains try: `<access origin="*" allows-arbitrary-loads-in-web-content='true'  />`


If you don't, try:
```
<access origin="http://www.mysite.com" />
```

**Comment by dalemugford** [comment]
That won't work for me, I need to access different apis, and just plopping in  `<access origin="*" allows-arbitrary-loads-in-web-content='true' />` my api `GET` doesn't load at all, `Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

**Comment by manucorporat** [comment]
@dalemugford ok!
can you try:
```
<access origin='*' allows-arbitrary-loads-in-media='true' allows-arbitrary-loads-in-web-content='true'  />
```

also, you said:
>In ionic serve with the browser set to ignore CORS restrictions everything works fine

can you make sure it works in your browser with CORS enabled? do not disable it

**Comment by dalemugford** [comment]
> can you make sure it works in your browser with CORS enabled? do not disable it

Yes, it works with CORS enabled, without issue. Both a call for Authorization (the client receives a JWT to use for `POST` requests), and `POST` requests themselves afterwards work fine.

`<access origin='*' allows-arbitrary-loads-in-media='true' allows-arbitrary-loads-in-web-content='true'  />
`
causes the same error `Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

Xcode says: `App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.`

**Comment by manucorporat** [comment]
ok.... shit

The only think I can imagine is to run your app in the iPhone Simulator and capture the traffic with Wireshark

**Comment by dalemugford** [comment]
Yeah it's a real head-banger!

I will set one up and post.

**Comment by dalemugford** [comment]
Ok here's the repo that replicates the issue, with only a single `POST` call. in serve you'll see the authentication token received, and in `wkwebkitview` in simulator or on device it fails.

https://github.com/dalemugford/-http-POST-failure-in-wkWebKitView

**Comment by ataraxus** [comment]
Hey Guys, I tried the new WK 2 Version and as expected had to change my server side to accept `http://ionic.local` as Origin instead of `null` which makes more sense. At least with my setup everything seems to work as expected!

**Comment by ataraxus** [comment]
@dalemugford i investigated you usecase and tried your example gist. @manucorporat i must confess i was astounded that it worked with ionic serve but not in the emulated ios device. I dug around and my best guess is, that there is something with the character encoding. 

If you look at the response with a hooked up safari you'll see that @dalemugford server answers: ```
{
    "code": "[jwt_auth] empty_username",
    "message": "<strong>ERROR</strong>: The username field is empty.",
    "data": {
        "status": 403
    }
}
```

if you copy this request which failed with WK2 as a curl:
```
curl 'http://www.findexapp.com/wp-json/jwt-auth/v1/token' -XPOST -H 'Content-Type: application/json;charset=UTF-8' -H 'Referer: http://ionic.local/Users/xxx/Library/Developer/CoreSimulator/Devices/E7CC167D-6D9A-4838-98F8-7C5616599873/data/Containers/Bundle/Application/D926D1E4-4F01-49C7-B326-8433F0EB0C64/WkWebKitView%20Issue.app/www/index.html' -H 'Origin: http://ionic.local' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C89 (140630588174112)' --data '{"sername":"testaccount","password":"k5wDDNczk%U9d$ZrQLZyg%eN"}'
``` 
it will succeed with: 
```
{"code":"[jwt_auth] empty_username","message":"<strong>ERROR<\/strong>: The username field is empty.","data":{"status":403}}
```
my best guess it has something to do how WK2 is encoding the request payload, which for what ever reason @dalemugford s server doesnt understand and responds with "username not provided"

**Comment by ataraxus** [comment]
This is really strange. I hooked up with wireshark and the actual request outgoing from WK2 does not have any content!
<img width="516" alt="bildschirmfoto 2017-01-27 um 15 36 45" src="https://cloud.githubusercontent.com/assets/1838191/22374452/8b4c931c-e4a6-11e6-9137-4f4392b9729d.png">

I actually copied the request api from my project into this gist and it doesn't work. 
I'm out of any ideas, my app does also use similar requests and they work fine. 
There could be something wrong with the project setup the ´config.xml´ was missing:
´´´
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
´´´

but even with that added it didnt work. maybe @manucorporat has a clue what could cause this behaviour.

**Comment by ChristianWeyer** [comment]
This seems to be exactly what we are seeing here: https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/94

**Comment by dalemugford** [comment]
@christianweyer I was thinking the same thing, that I might have to flip on https to get around it. I wonder if wkwebview is restricting post requests to secure https only?

**Comment by ataraxus** [comment]
@ChristianWeyer This is something worth investigating. my backend is https only

**Comment by ataraxus** [comment]
I verified this hypothesis. If i switch to HTTP WK2 will silently drop the content from the post. *Nice One*

This should give a warning and we have to state this in the docs . @manucorporat

**Comment by ChristianWeyer** [comment]
Do we already know where that issue comes from?

**Comment by ataraxus** [comment]
Security¿ XD i have no clue.... A hooked up Safari actually will show you the content!! If you don't have disregard or access to the server logs you'll be lost. No warnings whatsoever

**Comment by ChristianWeyer** [comment]
Yeah, we could only find out by using Wireshark.

**Comment by ThorConzales** [comment]
@manucorporat iframes indeed work!

**Comment by ckaeslin** [comment]
maybe that's the source of the problem: https://bugs.webkit.org/show_bug.cgi?id=138169#c25

looks also like there is a workaround which can maybe included here: https://github.com/WildDylan/WKWebViewWithURLProtocol

**Comment by ckaeslin** [comment]
I've changed https://github.com/driftyco/cordova-plugin-wkwebview-engine/blob/master/src/ios/CDVWKWebViewEngine.m#L80

to 

```
+ (BOOL)canInitWithRequest:(NSURLRequest *)request
{
    NSLog(@"%s %@", __func__, request.URL.absoluteString);
    NSLog(@"%s %@", __func__, [[NSString alloc] initWithData:request.HTTPBody encoding:NSUTF8StringEncoding]);
    return [[[request URL] host] isEqualToString:@"ionic.local"];
}
```
And body is always empty, no matter what I send.

**Comment by sfaizanh** [comment]
@dalemugford @ckaeslin have you guys found the solution yet? same issue over here

`POST` req.body is **undefined** when posting through simulator or device, works fine on chrome browser

**Comment by ataraxus** [comment]
Exept using HTTPS, nothing else yet

**Comment by sfaizanh** [comment]
Thanks @ataraxus

**Comment by sfaizanh** [comment]
If anyone wants SSL over remote ip, check [xip.io](http://xip.io/) for DNS and install SSL via [letsencrypt](https://letsencrypt.org/) 
*[Nginx Guide for letsencrypt](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04)
[Apache Guide for letsencrypt](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04)*

> **Note: For production buy domain and SSL**

**Comment by dalemugford** [comment]
I switched to using HTTPS (probably better anyways) for the stuff I'm doing at this point, but likely it's going to be problematic at some point when I need to leverage other APIs that don't offer ssl.

**Comment by sfaizanh** [comment]
@dalemugford you're right, it's an extra burden to setup every API with reverse proxy.

**Comment by dalemugford** [comment]
@sfaizanh it's besides the point anyways— there's hardly a security issue with `GET` requests to APIs over `HTTP`. I could understand the `POST` `PUT` `PATCH` `DELETE` being restricted for some reason.

**Comment by ataraxus** [comment]
OMG just stumbled upon this again. Having a local dev server with no SSL Cert and using a emulated iOS device. This setup is not working due WKWebKit omits post content used without SSL....

**Comment by JiaLiPassion** [comment]
I create a proxy server to avoid this problem, the code is here.
https://github.com/JiaLiPassion/cordova-plugin-wkwebview-engine

I just proxy the remote API call through localhost:8080/api served by GCDWebserver.
Is this idea ok for this issue?

**Comment by awadhajj** [comment]
I think this problem is related to angular Http service. I tried many many options to solve it but failed. Then i tried Cordova HTTP plugin instead of angular Http service, and now all is OK!!!

**Comment by JiaLiPassion** [comment]
@awadhajj , yes, use Cordova HTTP plugin can also resolve this issue, the side effort is , you can not debug your http request/response through safari remote debugging very easily and you have to convert your angular2 requestOptionsArgs to Cordova HTTP arguments.

**Comment by manucorporat** [comment]
Update to the current version of WK plugin! all the issues should have been fixed now

**Comment by sfaizanh** [comment]
@manucorporat any release or we use master branch?

**Comment by JiaLiPassion** [comment]
@manucorporat , thank you for the new release, but if server not enable cors, we will still get preflight request not success or other cors error when request remote API even with the GCDWebserver which brought into wkwebview-plugin 3.0, is that corrent?

**Comment by manucorporat** [comment]
@JiaLiPassion yes, CORS can't be disabled in WK

**Comment by manucorporat** [comment]
@sfaizanh master

remove everything cordova folder (plugins, platforms) and re add the platform ios

**Comment by sfaizanh** [comment]
@manucorporat Thanks

**Comment by JiaLiPassion** [comment]
@manucorporat , thank you! got it, so if server disable cors, I still need to use some native HTTP solution such as use cordova HTTP or use the GCDWebServer as a proxy, do you think the proxy should be a option feature and add into wkwebview? If so, I would like to make a PR to implement it, I am not sure that disable cors in server side is a common requirement or not.

**Comment by progresivoJS** [comment]
@ataraxus 👍  your solution save my day.

**Comment by awebdeveloper** [comment]
i am on 1.1.2-dev version I see the domain as localhost. I dont see `ionic.local`. why ?

`Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.`

**Comment by sneas** [comment]
Hey guys. Here is my solution to CORS issues with WKWebView. It is not a silver bullet. You can not use XMLHttpRequest directly. But you can use Angular `Http` service with it https://github.com/sneas/ionic-native-http-connection-backend

**Comment by daveshirman** [comment]
@sneas  I've been struggling this CORS issue for 2 days now.

I don't understand from your readme how I'm supposed to integrate this.  Can you give an example app.module.ts and usage?

Also, am I supposed to be removing HttpModule from the standard imports block?

```
  imports: [
    BrowserModule,
    HttpModule,
    IonicModule.forRoot(MyApp)
  ],
```

I'm THIS close to just saying f*ck it and reverting to UIWebview as that actually just works!

Thanks.

**Comment by sfaizanh** [comment]
@daveshirman is your Server URI scheme is http or https?

**Comment by sneas** [comment]
@daveshirman can you wrap your first endpoint request with `Platform.ready()`? So it looks like this

```
this.platform.ready().then(() => {
  this.http.get('url')
});
```

The reason for this is the library uses cordova plugin to perform HTTP requests which could be initiated in few seconds after app has started.

Right now I'm working on the new version of the lib which uses new `HttpClientModule` and eliminates the necessity of wrapping the first request in `Platform.ready`.

UPD

[Troubleshooting section](https://github.com/sneas/ionic-native-http-connection-backend#i-followed-the-installation-and-usage-instructions-but-still-receive-cors-issue-on-app-start) has been added to readme.

**Comment by daveshirman** [comment]
@sfaizanh the scheme is https, connecting to an AWS lambda function, with CORS enabled.

@sneas Thanks for your reply. 

I'm calling this **way** after the app has started, so platform ready isn't the issue.  I don't understand from your readme what changes to make in the app.module.ts though as I said.  

 **It's not clear whether I'm supposed to be removing the already existing HttpModule import in app.module.ts.**


Thanks for your assistance.

**Comment by sneas** [comment]
@daveshirman, you don't need the module in the example service.

All you need to do is to add `NativeHttpModule` into `imports` section of your app module and add `{provide: Http, useClass: Http, deps: [NativeHttpFallback, RequestOptions]}` into `providers` section of your app module.

**Comment by daveshirman** [comment]
@sneas ok, but do I also need to remove the existing HttpModule in the imports section like I asked?

I've done your integration but it still doesn't give anything other than http.status: 0 and url: null.

**Comment by sneas** [comment]
@daveshirman you don't need `HttpModule` in imports because it's provided by Ionic. Btw you can Slack me in ionic-worldwide.slack.com (dima)

**Comment by daveshirman** [comment]
@sneas ok, well having removed it as I said, I still am getting the same error.  
Is there anything else you can think of that I need to set up/change in the ionic config?  This isn't working right now following your import instructions.  Thanks.

**Comment by sneas** [comment]
@daveshirman does `window.cordovaHTTP2` exist on your device/emulator?

**Comment by daveshirman** [comment]
@sneas Now we're getting somewhere! Good catch.   So `window.cordovaHTTP2` is definitely undefined on both desktop browser + device (iOS).  The desktop I would expect as there's no cordova either.

I've checked that the plugins are installed and in the `ios.json` file too:

```
        "cordova-plugin-advanced-http": {
            "PACKAGE_NAME": "com.mydomain.myapp"
        }
```

**Comment by sneas** [comment]
@daveshirman you have to run `ionic cordova plugin add cordova-plugin-http2` to install the needed plugin and make sure it exists in the device environment. Also for your attention: this will not affect your browser environment in any way. When running in browser `ionic-native-http-connection-backend` makes requests with regular `XmlHttpRequest`. And when running on device it uses `cordova-plugin-http2` to perform requests.

**Comment by daveshirman** [comment]
@sneas Ok, well I'd already done that as I stated. But I removed and re-added and it is defined now.  Now my uploads are going to the server (S3 bucket) but the policy is complaining that there should only be one parameter specified.  

Is there anything you're doing in your module that modifies the payload at all that isn't documented?

Thanks for all your help, greatly appreciated.

**Comment by sneas** [comment]
@daveshirman, no the library does not modify payload. I can have a closer look if you share an example of request which works correctly with UIWebView but not with the library.

**Comment by daveshirman** [comment]
@sneas Ok, thanks for your help, but I'm now running into the issue with Android not compiling now because .patch method isn't supported - which I saw in your known issues.  This isn't the right approach to fixing the issue I think.  Thanks.

**Comment by Piraban** [comment]
will they fix it or any solution?  ionic is headache

**Comment by stellmaurer** [comment]
The solution for me was to use UIWebView instead of WKWebView. Follow the steps in the link to do that, http://uncaughterror.com/programming/ionic3/preflight-response-issue-with-ionic3-app-on-ios-build-only-resolved/.

**Comment by caferelgin** [comment]
I got it working using WKWebView after adding the following lines to config.xml;

`<platform name="ios">`
&nbsp;`<access origin="http://localhost:8080" />`
&nbsp;`  <allow-navigation href="http://localhost:8080/*" />`
`</platform>`

Cheers!

**Comment by sahibjotsingh** [comment]
@caferelgin Thanks. I tried your approach, but it didn't work.
